id: P005442
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22318
  title: སྨན་བླའི་ཆོག་བསྒྲིགས་འདོད་དགུའི་འབྱུང་གནས
  author: ''
  volumes:
    64bf02e67a08467da0ace43dbf52883e:
      image_group_id: I1PD36241
      title: ''
      volume_number: 1
      total_pages: 156
      base_file: v001.txt
