id: I317CCAC1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:29:42+00:00'
last_modified: '2022-06-08T03:07:07.029078+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22318
  title: སྨན་བླའི་ཆོག་བསྒྲིགས་འདོད་དགུའི་འབྱུང་གནས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8226':
      image_group_id: I1PD36241
      title: ''
      total_pages: 156
      order: 1
      base_file: 8226.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
